### PR TITLE
Docker-based CI

### PR DESCRIPTION
**Pull request by bochecha**
This is based off of @yookoala's work in #99 

I rebased it on the latest master, cleaned it up a bit, and made some modifications:

* I removed the `local` testing, as there's really no point
* I parametrized the `FROM` line so that we have a single Dockerfile (as already was the case for the original pull request) but in a way we can still have automatic builders in the Docker Hub

That last point is a big unknown: I have no clue whether it works at all. :D 

However, this suggests it should: https://github.com/docker/hub-feedback/issues/508#issuecomment-222520720

### CODE REVIEW

**Comment by yookoala** [comment]
Please see: https://github.com/Cangjians/libcangjie/pull/99#discussion_r138641103

**Comment by bochecha** [comment]
> * I parametrized the FROM line so that we have a single Dockerfile (as already was the case for the original pull request) but in a way we can still have automatic builders in the Docker Hub
> 
> That last point is a big unknown: I have no clue whether it works at all. :D

And it doesn't seem to work: https://travis-ci.org/Cangjians/libcangjie/jobs/275110216

This should work, as per https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact

Except that feature started being available in [Docker 17.05.0](https://docs.docker.com/release-notes/docker-ce/#17050-ce-2017-05-04), and Travis runs 17.03.1. 😭 

God, I hate Travis more each day.

**Comment by yookoala** [comment]
That's a neat new feature in Dockerfile. I only wish it were available for Travis.

**Comment by bochecha** [comment]
@yookoala It works! 😄

**Comment by bochecha** [comment]
Ok, so now we've got:

* a single `Dockerfile` for libcangjie
* a CI which runs on multiple OSes (all the ones for which we have build-essential images)
* the automatic builds in the Docker Hub are [working just fine](https://hub.docker.com/r/cangjians/libcangjie/builds/bxozjfwnbbmtxwlafravw34/)

Which is pretty great. 😃

**Comment by bochecha** [comment]
Oops, you merged. 😛 

> Before merging this, we need to configure things properly there.

I'll go do that now, and trigger the builds manually. 😉

**Pull request merged**
