### PR TITLE
table.txt fixed with my own data -- old, please see #98

### PR DESCRIPTION
**Pull request by boyin**
All 4- and 5-digit numbers are line numbers in the original table.txt file

1.  MISTAKE: CORRECTIONS / MISSING ENCODINGS

7164 -xnem 丞 there seems to be no other char with encoding NEM, certainly no useful ones.
7165 +hgi 丟 else hgi and mgi go to different chars (one 丟 and one non-big5 char) causing confusion, 
                    this is a big5 first method anyways, so hgi is assigned to the big5 char as main encoding
7282 -ttx 井 this is a mistake (CJ3 is always 井 tt, big5 order)
10034 xyck 奕 reformat to comply with regular list form
12315 -isbt 扁 conformity with MacOS/Win and solves problem with 盛
15624 -jcegg 漥 mix-up with 窪 jcegg (also only big5 char at ejcg!)
21172 -tyrv 蓑 mix-up, should always have tywv

2.     SC/TC confusions

7491 -omro + omfm 佥(僉)
11912 -gep + gbhp 悫(愨)

3. 
    REMOVED EXTRA X ENCONDING FROM SOLE TC BIG5 CHAR
    If there corresponding non-big5 char listed is useful, it gets an X encoding  (marked "+") 
7418 -xommi 伝 会+ 15576 -xejpu 滵 浇+
7375 -xol 仲 个+ 15636 -xedlo 漱 濑+
7451 -xomfo 伾 佥+ 16083 -xfbnd 烰 学+
8147 -xvl 凵 丩+妕 16823 -xmgkl(d) 珔 臶
8188 -xbmln 刞 删+ 17127 -xmgmv(n) 甄 珁
8228 -xiiln 剆 剗+ 17374 -xkhpa 痻 狥
8535 -xnems(u) 巹 卺 17534 -xhaha(j) 皞 皡
9066 -xrypd 喍 嘑+ 18924 -xhdlo 簌 籁
10481 -xvnum 嬔 嬎 19294 -xvfna(u) 絻 絶+
10841 -xushi 屻 岃 19536 -xtbli 繭 萤+
10919 -xhru 峊 乱+ 19924 -xhjsm(m) 翱 翶+
11019 -xuwjr 崮 崮崓 20216 -xbnau 脕 脃
11128 -xukcf 嶚 嶛 20418 -xbtis 臟 臓
11153 -xhku 嶴 岙 20609 -xtmon 芞 萮
11817 -xplmo 恌 愦+ 20617 -xtoll 芥 养+
12037 -xgep 愨 悫 21145 -xtvfh 蒶 𦯷䔋
12099 -xikp 慦 龙+ 21427 -xtbhu 藐 苋+
12680 -xqsje 掫 摄+ 22369 -xmub 襾 両
12854 -xqwli 擉 摆+ 22428 -xbuho(k) 覹 矀
13044 -xqipd 攗 攈 22814 -xyrhd(n) 謻 誗
14254 -xdhaj 槔 槹 24627 -xcolb 鉓 鏅
14525 -xdine 櫠 栐 24678 -xcyiu 銃 鋶
14894 -xepi 汋 沟+ 24961 -xchwp 鎞 鏓
14947 -xenin 沀 汿+ 26431 -xmkoi(v) 饜 饏

4. involves duplicate characters both of which are known since Cangjie's big5-only days. There are (a) there is a missing (in my opinion) version 3 X encoding; (b) the version 5 X encoding is different from the version 3 encoding, which is done in big5 order. Since this version of libcangjie only sorts in big5 order, I flipped the X and non-X encodings since otherwise the X encoding is useless; (c) both of the above.  These are too numerous to list

### CODE REVIEW

**Comment by bochecha** [comment]
Hi, thanks for the contribution.

There are a few problems which must be resolved before we can merge it, though.

First, the branch has conflicts with master. This is because you started your fixes off of an old master, and changes happened in master since then.

Please rebase your changes on the latest master first.

Secondly, a big thing is missing from this: **why** are those changes important?

Your pull request comment seems to imply that there are 4 different changes being made, so please do them as 4 separate commits.

And for each of them, the **commit message** should explain why this is the right thing to do.

Remember that I'm not a Chinese scholar, and I've never even used Cangjie, so I rely on people like you to explain to me why things are wrong with our data and how to fix them. 😃

**Comment by boyin** [comment]
Secondly, a big thing is missing from this: *why* are those changes
> important?
>
> Your pull request comment seems to imply that there are 4 different
> changes being made, so please do them as 4 separate commits.
>
> And for each of them, the *commit message* should explain why this is the
> right thing to do.
>
 I am sorry, will try to split the commits into 3-4 and comment on each of
them separately and do that soon,

-- Bo-Yin

**Comment by bochecha** [comment]
> will try to split the commits into 3-4

Just to be clear, it's fine to keep them inside a single pull request. :)

**Comment by boyin** [comment]
In the HEAD commit 61c7543674267127edee469211bfb0716808abc1
now there are  three commits

1. mistakes 
2. X encodings not usually found in the duplicated char lists 
3. X encodings of chars usually found in the duplicated char lists

Please examine and see if you agree with my proposed changes.

**Comment by boyin** [comment]
This will teach me never to use -f in git, I was totally unable to unwind my way out of the resulting mess. As a result, I deleted the forked repo, re-checked out the original repo, re-committed.

Please close thisr pull request if it does not disappear on its own with the first star-crossed repo.

**Comment by boyin** [comment]
I hope that it is now ok in 3 commits ....

**Comment by bochecha** [comment]
We have moved to Freedesktop: https://gitlab.freedesktop.org/cangjie/libcangjie

Please continue discussion there.

**Pull request closed without merging**
