### PR TITLE
Second attempt to pull request

### PR DESCRIPTION
**Pull request by boyin**
This will teach me never to use -f in git, I was totally unable to unwind my way out of the resulting mess.  As a result, I deleted the forked repo, re-checked out the original repo, re-committed.

Please close the other pull request if it has not vanished with the first star-crossed repo.

### CODE REVIEW

**Comment by bochecha** [comment]
Thanks for redoing the pull request, this is now much clearer.

One thing I just saw in your commit messages bothers me:

> AS A RESULT, EVEN CJ5 WILL HAVE THE X ENCODINGS OF CJ3.  IT
> IS A CONSEQUENCE OF How libcangjie functions.

We shouldn't modify the data just to adapt it to the way libcangjie works. We should instead modify libcangjie to make it return the correct results with the correct data.

So in this case, the right question is: should CJ5 really have those CJ3 X-encodings?

If the answer is "no", then we should not add them. If that means changing the way libcangjie works, then let's do that.

**Comment by boyin** [comment]
_So in this case, the right question is: should CJ5 really have those CJ3 X-encodings? If the answer is "no", then we should not add them. If that means changing the way libcangjie works, then let's do that._

Unsurprisingly, my answer to that question is **yes**.  And the reason is the one which I believe CBF made one of the central tenets of his system: _As much as possible each Chinese character should have one distinct encoding, such that a typist can type Chinese using the letters plus the space key. (27 keys), without ever needing to look at the screen or to pick among alternatives, if at all possible._  

Otherwise, why are they X encodings at all, much less useless X encodings?

If you believe my point, then it follows that: **if there is a pair of characters each of which are at all useful and they have the same encoding, then we should add an X encoding to make collisions less likely.**

There are maybe two ways in which "how libcangjie works" should be changed.  

1.  to resolve as many pairs of characters of the same encoding with X encodings.  
2.  to make the output of colliding encodings more in accordance of how frequently they are used.  

Please note that in the latter, we do not want the result to be adaptive at all.  We want the result to be deterministic (again, so you will never need to read the screen).

My patches address only the first point.

**If the answer is not to accept these patches, I still offer to redo the third commit/patch again, such that CJ5 will have CJ5 X encodings, even if useless.**

**Comment by boyin** [comment]
Side note on _how to make the output of colliding encodings more in accordance of how frequently they are used_ (but still deterministic).  

I guess there are other supporters for such a possible change, since in perusing some previous discussions I saw that there is at least one developer who would like to see CJ5-like ordering (and presumably CJ5-like X encodings to go with it) in CJ3. 

We can achieve that by 

1. switching the order numbers of the characters in question (now both CJ3 and CJ5 will have CJ5-like orderings and X-encodings, ideally)
2. when returning the list of characters, go through the characters and their encodings, and put any big5 character which has an X encoding for the same input.

Example for choice 2 is the following: input is OKR, libcangjie first find 佑 and 知 in big5 order, but note that 佑 has the encoding XOKR, and order it behind other big5 characters. Thus, the default for OKR becomes 知, with the duplicate character being 佑, which can be entered via XOKR.

Similarly, VID returns 槳 and 樂 in big5 order, but libcangjie notices that 槳 has the encoding XVID, and order it behind 樂, which become the default character for VID.

IPP would return 庇態忒 in big5 order, and libcangjie notices that 庇 has XIPP and 忒 has XXIPP (these are actual encodings in MacOS Cangjie), and returns the characters in the order 態 庇 忒

but this is probably a bigger change in libcangjie than just changing the database.

**Comment by bochecha** [comment]
>> So in this case, the right question is: should CJ5 really have those CJ3 X-encodings? If the answer is "no", then we should not add them. If that means changing the way libcangjie works, then let's do that.
> 
> Unsurprisingly, my answer to that question is yes. And the reason is the one which I believe CBF made one of the central tenets of his system: *As much as possible each Chinese character should have one distinct encoding, such that a typist can type Chinese using the letters plus the space key. (27 keys), without ever needing to look at the screen or to pick among alternatives, if at all possible.*
> 
> Otherwise, why are there X encodings at all, much less useless X encodings?
> 
> If you believe my point, then it follows that: if there is a pair of characters each of which are at all useful and they have the same encoding, then we should add an X encoding to make collisions less likely.

Your answer doesn't seem to actually address my question, but maybe that's because I wasn't clear enough. 😉 

What you're saying in the text I just quoted is that X-encodings are useful and desirable, since they allow deduplicating characters which would otherwise share the same radical decomposition. There is no question about that, I'm pretty sure we all agree this is the case.

What I was specifically asking is not why you were adding X-encodings to some characters, but why you were adding **CJ3 X-encodings to some characters in CJ5**.

Shouldn't CJ5 have its own X-encodings? (They might or might not be the same as the CJ3-encodings for each character, of course, depending on whether or not the character has the same encoding in CJ3 and CJ5.)

> in perusing some previous discussions I saw that

When referencing previous discussions, please link to it, as that helps reminding everyone of the context for such past discussions.

> Example for choice 2 is the following: input is OKR, libcangjie first find 佑 and 知 in big5 order, but since 佑 has the encoding XOKR, in this vision libcangjie will order it behind other big5 characters. Thus, the default for OKR becomes 知, with the duplicate character being 佑, which can be entered via XOKR.
> 
> Similarly, VID returns 槳 and 樂 in big5 order, but our putative new libcangjie notices that 槳 has the encoding XVID, and order it behind 樂, which become the default character for VID.
> 
> IPP would return 庇態忒 in big5 order, and the new libcangjie notices that 庇 has XIPP and 忒 has XXIPP (these are actual encodings in MacOS Cangjie), and returns the characters in the order 態 庇 忒
> 
> but this is probably a bigger change in libcangjie than just changing the database!

This kind of change is exactly what I had in mind above when I said « If that means changing the way libcangjie works, then let's do that ». 😉 

We shouldn't limit ourselves to whatever is the smallest change or the easiest/quickest to do.

If something big needs to be done, and if it is the right thing, then we should do it.

**Comment by boyin** [comment]
So should I script reverse-changes such that  all X -encodings in CJ5 follows "standard practices" (CBF's publications, MacOS, Windows) while X-encodings for CJ3 follows big5 order (which is their normal order) _**even though they would be useless as things stand**_? I guess I can do that too.  This basically only affect the third commit.

**Comment by bochecha** [comment]
> such that all X -encodings in CJ5 follows "standard practices" (CBF's publications, MacOS, Windows)

From what I understood, in CJ5 the goal is that when a collision (two characters with the same radical decomposition) happens, the most frequently used one should get the canonical encoding, and the other ones should get an `x` prepended to the canonical encoding. The least useful the character, the more `x` it would have.

Is that correct?

If so, then I would say that this is what we should strive for.

> even though they would be useless as things stand

Why would they be useless?

---

Overall, thanks for your commitment to this. I know you started working on this a while ago, and we haven't always been very available to support you. I truely appreciate your efforts to try and improve libcangjie. 😄 

Also, in all discussions regarding the ordering of characters, there are two things to keep in mind though:

1. Cangjie (倉頡) typists will want the ordering to allow for fastest possible speed, which means the most commonly used character first, the other ones with the X-encoding
2. Quick (速成) typists will want... the same ordering as on Windows

So far, we have privileged the second group in libcangjie, because they seem to be the most numerous ones, at least they are the ones I have access to help me.

That means the order currently returned for Cangjie might be suboptimal, because it is the (hopefully) best ordering for Quick.

Eventually we might have to divorce these two, so that the ordering for Cangjie will be different from the ordering for Quick.

I feel the current discussion might lead us down that path. I guess we'll just have to do it if it's the right thing to do, of course, but I felt I had to mention it so we really are on the same page. 😃

**Comment by boyin** [comment]
Let me split my answers here ...

> From what I understood, in CJ5 the goal is that when a collision (two characters with the same radical decomposition) happens, the most frequently used one should get the canonical encoding, and the other ones should get an x prepended to the canonical encoding. The least useful the character, the more x it would have. Is that correct? 

That was possibly the goal, but in all versions of Cangjie, 已 (already) is XSU and 己 (self) is SU, even though the former is more frequent (you would learn this if you used windows, because it tried to be adaptive).  But it is ok, because you just remember the few exceptions. I wouldn't switch 已 and 己 around, I and the few people who uses Cangjie have gotten used to it.  Similarly because I have used both CJ3 and CJ5, I was able to adjust by adjusting to "big5 order (CJ3 style) X encodings"

I conjecture that CBF decided in CJ5 that **where the frequency difference is obvious**, he is going to deviate from the big5 (CJ3) order as to which is the canonical character and which is the duplicate.  He must have thought that the difference between 已 and 己 is not very large. 

Note that CBF's decisions, at least as far as CJ5 goes, mostly makes sense, but there are some which are arguable.  In the end you just have to memorize those handful, follow tradition, whatever, because what is obvious to one is not to another.  Other examples where I would disagree with the current ordering in CJ5 about frequency are

ormbc 頜 (anatomic part, the muscles and bones around the mouth) xormb 頷 (slight nod)
rmmr 跖 (the name of a famous ancient bandit, but a dead character otherwise) xrmmr 唔 ("hm")
oge 雙 (pair) xoge 隻 ("item of", usually a long stick-like thing or an animal, most often a bird)
mre 砅 (I have no idea) xmre 泵 (pump ... what was CBF thinking?) 

>> _even though they would be useless as things stand_
> Why would they be useless?

_As things stand_ they would be extraneous.  I am not saying they are useless in general.  If we make libcangjie check which character has the x encoding for example they would become useful.

**Comment by boyin** [comment]
> Overall, thanks for your commitment to this. I know you started working on this a while ago, and we haven't always been very available to support you. I truely appreciate your efforts to try and improve libcangjie. :smile:

Why, thank you!! :smile:  I am sure I must have sounded like the proverbial bull in the china shop when I barged in, but I figured that whatever work I am doing it is good for myself at least, so it was easy to justify to myself the time expenditure, which wasn't that much (I was unwell for a while).

> Also, in all discussions regarding the ordering of characters, there are two things to keep in mind though:
> 

> - Cangjie (倉頡) typists will want the ordering to allow for fastest possible speed, which means the most commonly used character first, the other ones with the X-encoding
> - Quick (速成) typists will want... the same ordering as on Windows

> So far, we have privileged the second group in libcangjie, because they seem to be the most numerous ones, at least they are the ones I have access to help me.
> 
> That means the order currently returned for Cangjie might be suboptimal, because it is the (hopefully) best ordering for Quick.
> 
> Eventually we might have to divorce these two, so that the ordering for Cangjie will be different from the ordering for Quick.

I thought about this before and my answer to that is, we can do one of three things

- make the reordering a checkbox, in which case the Quick typists simply uncheck it
- make the reordering a CJ5 feature only, in which case the Quick typists sticks to CJ3 ordering and everything doesn't change.  CJ3 typists are helped by having X encodings but perhaps less than if they have the option to switch to CJ5-like X encodings.  On the other hand their barrier to entry is lower (so instead of OKR[space]2 to input 知, they now input OKRX, and they still input OKR[space] to input 佑).  
- simply skip the reordering for Quick

> What I was specifically asking is not why you were adding X-encodings to some characters, but why you were adding CJ3 X-encodings to some characters in CJ5.

Ah.  Ok, so from
> There are maybe two ways in which "how libcangjie works" should be changed.
> 1. to resolve as many pairs of characters of the same encoding with X encodings.
> 2.  to make the output of colliding encodings more in accordance of how frequently they are used.
these are somewhat orthogonal questions, and I was seeking to _answer one of them first,_ so addressing point 1.

So I wasn't trying to  add CJ3 X encodings (X at the back, as in OKRX for 知), I was adding CJ5 X encodings (X at the front) but in the CJ3 order/style (big5 order straight up, so XOKR for 知 and not for 佑).

**Comment by boyin** [comment]
Hello,

I have done some scripting to be exact I can scan a list now of "CJ5 reversals" and the table.txt I had, so that on seeing "抓 掀 qhlo" it generates a diff file something like this 

:
:
12400c12400
< 抓 抓 1 1 0 0 1 0 0 0 0 qhlo qhlo NA 22290
---
> 抓 抓 1 1 0 0 1 0 0 0 0 qhlo qhlo,xqhlo NA 22290
:
:
12637c12637
< 掀 掀 1 1 0 0 1 0 0 0 0 qhlo,qhlox qhlo,xqhlo NA 19766
---
> 掀 掀 1 1 0 0 1 0 0 0 0 qhlo,qhlox qhlo NA 19766
:
:

So we now can select any of those pairs to reverse the CJ5 X encodings.
So, once the code that reorders the characters returned based on who has x encodings is ready, the X encodings can be switched around easily.

the list of characters which has cj3-cj5 X encoding reversals are

暉 暈 abjj      顃 纇 ffmbc     烋 煲 odf       茱 孽 thjd
顥 顯 afmbc     焓 熗 foir      伙 尒 of        菺 萹 thsb
冕 晚 anau      縠 鷇 gfhne     鷡 鷦 ofhaf     芅 懟 tip
旼 旻 ayk       劫 勢 giks      隻 雙 oge       萓 靻 tjbm
郥 鄍 bcnl      嗀 嗀 grhne     侂 飥 oihp      苧 靪 tjmn
冗 肌 bhn       欯 歖 grno      佑 知 okr       莞 靰 tjmu
冊 皿 bt        垶 墇 gytj      偯 儴 oyrv      鴱 鶧 tkhaf
瞚 矉 bujmc     鄮 酇 hcnl      旨 旬 pa        芋 某 tmd
睢 瞿 buog      邸 郵 hmnl      悷 憿 phsk      鄞 邯 tmnl
鳻 鵜 chhaf     郈 郜 hrnl      勺 勾 pi        茌 萑 tog
鏔 鑌 cjmc      郋 郳 hunl      勼 恞 pkn       鄀 鄯 trnl
鈦 鈜 cki       鶹 鷭 hwhaf     匉 怦 pmfj      苨 懃 tsp
釚 銕 ckn       鄘 郙 ibnl      恉 恂 ppa       鵧 鷁 tthaf
弚 鈏 cnl       慼 憑 ifp       悃 惈 pwd       孳 藥 tvid
朹 桋 dkn       庇 態 ipp       抓 掀 qhlo      曲 苗 tw
枑 桱 dmvm      怠 感 irp       捩 撽 qhsk      茵 奠 twk
杼 栘 dnin      弁 戒 it        搣 摵 qihf      峷 嶂 uytj
框 櫂 dsmg      剋 剜 juln      撾 揥 qybb      鷥 鸞 vfhaf
梱 棵 dwd       鴳 鶈 jvhaf     揨 攍 qyrn      紁 紎 vfik
梓 樟 dytj      猏 猵 khhsb     唳 噭 rhsk      縯 繽 vfjmc
榱 櫰 dywv      郁 郗 kbnl      戢 戰 rji       姅 攣 vfq
灝 灦 eafc      痲 癲 kjcc      啀 跬 rmgg      奘 奊 vgk
濉 灈 ebug      鴐 鵸 krhaf     唔 跖 rmmr      槳 樂 vid
漇 漎 ehoo      羍 痒 ktq       鴞 鶚 rshaf     困 果 wd
淚 激 ehsk      尢 疝 ku        咡 咠 rsj       鷝 鸅 wjhaf
瀩 灒 ehuc      螾 蠙 lijmc     鳭 鷚 shhaf     欳 歊 ybno
濂 瀇 eitc      冑 胄 lwb       屧 髹 shod      皻 皽 ymdhe
氿 洟 ekn       琀 瑲 mgoir     屐 履 shoe      迆 柴 ypd
沍 涇 emvm      玫 致 mgok      邵 郡 srnl      詣 詢 yrpa
汫 洴 ett       泵 砅 mre       妀 媐 suv       乩 訕 yru
涃 淉 ewd       砍 歌 mrno      鶼 鷬 tchaf     鴗 鸕 ythaf
滖 瀤 eywv      弔 引 nl        欺 歉 tcno      
熒 爣 ffbf      久 欠 no        菞 蕛 thdh

**Comment by boyin** [comment]
Is there anyone still watching this?

**Comment by bochecha** [comment]
We have moved to Freedesktop: https://gitlab.freedesktop.org/cangjie/libcangjie

Please continue discussion there.

**Pull request closed without merging**
