### PR TITLE
data: Split the short codes to their own lines

### PR DESCRIPTION
**Pull request by bochecha**
Currently, the frequency is associated to a character and all its codes, except for a single exception.

We are about to split multiple codes for any given character so that the frequency becomes instead associated to a code for a given character. (see #104)

This commit splits the short codes to their own lines, so that they can have their own frequencies, separated from the frequencies associated to each Cangjie 3 and 5 codes.

### CODE REVIEW

**Comment by yookoala** [comment]
I don't quite follow this. The changes seems only applied to punctuation characters.

**Comment by yookoala** [comment]
Oh. I think I get you now. You're separating the short code frequencies from the Cangjie typing frequencies of those punctuation characters.

**Review by yookoala — APPROVED** [review]
Seems reasonable.

**Comment by bochecha** [comment]
> Oh. I think I get you now. You're separating the short code frequencies from the Cangjie typing frequencies of those punctuation characters.

Exactly.

The goal being to make it possible/easier to fix #104 with a script and review those changes without being bothered by this trivial change here. :slightly_smiling_face:

**Pull request merged**
